@host=http://localhost:3000
@jobId=1

### Submit a Job (PROCESS_DATA)
POST {{host}}/jobs
Content-Type: application/json

{
  "type": "process_data",
  "data": {
    "input": "example input",
    "options": {}
  }
}

### Submit a job (FILE_PROCESSING)
POST {{host}}/jobs
Content-Type: application/json

{
  "type": "file_processing",
  "data": {
    "filename": "example.jpg",
    "size": 1024000
  }
}

### Get Job Status
GET {{host}}/jobs/{{jobId}}

### List Jobs
GET {{host}}/jobs?status=completed

### Delete a Job
DELETE {{host}}/jobs/{{jobId}}
